services:
  # PostgreSQL Database Service
  db:
    image: postgres:15-alpine
    container_name: money-transfer-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transferdb
    ports:
      - "5432:5432"
    volumes:
      # Mount the init script to initialize the database on startup
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # Persist data
      - postgres-data:/var/lib/postgresql/data

  # .NET Backend Service
  backend:
    image: agb-backend:v2.0
    container_name: money-transfer-backend
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=15.15.15.33;Port=5432;Database=transferdb;Username=user;Password=password
    depends_on:
      - db
    networks:
      - postgres-pgadmin


    
  frontend:
    image: agb-frontend:v2.0
    container_name: money-transfer-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@agb.dz
      PGADMIN_DEFAULT_PASSWORD: PaSSwD
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - postgres-pgadmin

volumes:
  postgres-data:
  pgadmin-data:

networks:
  postgres-pgadmin: